sudo: required

language: java

jdk: oraclejdk8

services:
  - docker

before_install:
  - docker pull hyperledger/fabric-peer:amd64-1.3.0
  - docker pull hyperledger/fabric-ca:amd64-1.3.0
  - docker pull hyperledger/fabric-tools:amd64-1.3.0
  - docker pull hyperledger/fabric-orderer:amd64-1.3.0
  - docker pull hyperledger/fabric-ccenv:amd64-1.3.0
  - docker pull hyperledger/fabric-couchdb:amd64-0.4.14
  - docker tag hyperledger/fabric-ca:amd64-1.3.0 hyperledger/fabric-ca:latest
  - docker tag hyperledger/fabric-peer:amd64-1.3.0 hyperledger/fabric-peer:latest
  - docker tag hyperledger/fabric-orderer:amd64-1.3.0 hyperledger/fabric-orderer:latest
  - docker tag hyperledger/fabric-tools:amd64-1.3.0 hyperledger/fabric-tools:latest
  - docker tag hyperledger/fabric-ccenv:amd64-1.3.0 hyperledger/fabric-ccenv:latest
  -

  - docker images

install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - mvn clean test jacoco:report coveralls:report